name: Build

# Controls when the action will run. 
on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_call:

jobs:
  publish:
    name: ${{ matrix.os }} ${{ matrix.config }} (UE ${{ matrix.version }})
    runs-on: [self-hosted, UE-${{ matrix.version }}, ${{ matrix.os }}]
    strategy:
      fail-fast: false
      matrix:
        name: SaveExtension
        config: [Debug, Release]
        os: [Windows, Linux]
        version: "5.3"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Piperift Scripts
        run: git clone https://github.com/PipeRift/CICDScripts Scripts

      - name: Build Plugin
        run: py ./Scripts/build.py plugin

